services:
  bluebook:
    build:
      context: .
      network: host
    image: bluebook
    container_name: BlueBook
    ports:
      - "${PORT}:3000"
    volumes:
      - data:/app/data
    restart: unless-stopped

volumes:
  data:
