services:
  bluebook:
    build: .
    image: bluebook
    container_name: BlueBook
    ports:
      - "${PORT}:3000"
    volumes:
      - data:/app/data
      - ./src:/app/src
    restart: unless-stopped

  pandoc:
    platform: linux/amd64
    build: 
      context: ./pandoc
    image: pandoc
    container_name: Pandoc
    volumes:
      - ./pandoc/src:/app/src

volumes:
  data:
